// @ts-nocheck
import * as __fd_glob_65 from "../content/docs/support/sponsor.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/support/sponsor.en.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/support/security.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/support/security.en.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/support/donate.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/support/donate.en.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/support/community.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/support/community.en.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/overview/third-party-prompt-repositories.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/overview/third-party-prompt-repositories.en.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/overview/render.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/overview/render.en.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/overview/quick-start.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/overview/quick-start.en.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/overview/project-structure.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/overview/project-structure.en.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/overview/production-readiness.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/overview/production-readiness.en.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/overview/page-gallery.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/overview/page-gallery.en.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/overview/low-memory.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/overview/low-memory.en.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/overview/features.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/overview/features.en.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/overview/docker.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/overview/docker.en.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/overview/configuration.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/overview/configuration.en.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/progress/todo.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/progress/todo.en.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/progress/pending-test.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/progress/pending-test.en.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/business/license.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/business/license.en.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/business/commercial-launch.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/business/commercial-launch.en.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/business/cla.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/business/cla.en.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/business/business.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/business/business.en.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/canvas/canvas-shortcuts.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/canvas/canvas-shortcuts.en.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/canvas/canvas-node-manual.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/canvas/canvas-node-manual.en.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/backend/local-development.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/backend/local-development.en.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/backend/canvas-data-structure.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/backend/canvas-data-structure.en.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/backend/backend-database.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/backend/backend-database.en.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/backend/api-response.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/backend/api-response.en.mdx?collection=docs"
import { default as __fd_glob_13 } from "../content/docs/progress/meta.json?collection=docs"
import { default as __fd_glob_12 } from "../content/docs/progress/meta.en.json?collection=docs"
import { default as __fd_glob_11 } from "../content/docs/support/meta.json?collection=docs"
import { default as __fd_glob_10 } from "../content/docs/support/meta.en.json?collection=docs"
import { default as __fd_glob_9 } from "../content/docs/overview/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/overview/meta.en.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/canvas/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/canvas/meta.en.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/business/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/business/meta.en.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/backend/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/backend/meta.en.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.en.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.en.json": __fd_glob_0, "meta.json": __fd_glob_1, "backend/meta.en.json": __fd_glob_2, "backend/meta.json": __fd_glob_3, "business/meta.en.json": __fd_glob_4, "business/meta.json": __fd_glob_5, "canvas/meta.en.json": __fd_glob_6, "canvas/meta.json": __fd_glob_7, "overview/meta.en.json": __fd_glob_8, "overview/meta.json": __fd_glob_9, "support/meta.en.json": __fd_glob_10, "support/meta.json": __fd_glob_11, "progress/meta.en.json": __fd_glob_12, "progress/meta.json": __fd_glob_13, }, {"backend/api-response.en.mdx": __fd_glob_14, "backend/api-response.mdx": __fd_glob_15, "backend/backend-database.en.mdx": __fd_glob_16, "backend/backend-database.mdx": __fd_glob_17, "backend/canvas-data-structure.en.mdx": __fd_glob_18, "backend/canvas-data-structure.mdx": __fd_glob_19, "backend/local-development.en.mdx": __fd_glob_20, "backend/local-development.mdx": __fd_glob_21, "canvas/canvas-node-manual.en.mdx": __fd_glob_22, "canvas/canvas-node-manual.mdx": __fd_glob_23, "canvas/canvas-shortcuts.en.mdx": __fd_glob_24, "canvas/canvas-shortcuts.mdx": __fd_glob_25, "business/business.en.mdx": __fd_glob_26, "business/business.mdx": __fd_glob_27, "business/cla.en.mdx": __fd_glob_28, "business/cla.mdx": __fd_glob_29, "business/commercial-launch.en.mdx": __fd_glob_30, "business/commercial-launch.mdx": __fd_glob_31, "business/license.en.mdx": __fd_glob_32, "business/license.mdx": __fd_glob_33, "progress/pending-test.en.mdx": __fd_glob_34, "progress/pending-test.mdx": __fd_glob_35, "progress/todo.en.mdx": __fd_glob_36, "progress/todo.mdx": __fd_glob_37, "overview/configuration.en.mdx": __fd_glob_38, "overview/configuration.mdx": __fd_glob_39, "overview/docker.en.mdx": __fd_glob_40, "overview/docker.mdx": __fd_glob_41, "overview/features.en.mdx": __fd_glob_42, "overview/features.mdx": __fd_glob_43, "overview/low-memory.en.mdx": __fd_glob_44, "overview/low-memory.mdx": __fd_glob_45, "overview/page-gallery.en.mdx": __fd_glob_46, "overview/page-gallery.mdx": __fd_glob_47, "overview/production-readiness.en.mdx": __fd_glob_48, "overview/production-readiness.mdx": __fd_glob_49, "overview/project-structure.en.mdx": __fd_glob_50, "overview/project-structure.mdx": __fd_glob_51, "overview/quick-start.en.mdx": __fd_glob_52, "overview/quick-start.mdx": __fd_glob_53, "overview/render.en.mdx": __fd_glob_54, "overview/render.mdx": __fd_glob_55, "overview/third-party-prompt-repositories.en.mdx": __fd_glob_56, "overview/third-party-prompt-repositories.mdx": __fd_glob_57, "support/community.en.mdx": __fd_glob_58, "support/community.mdx": __fd_glob_59, "support/donate.en.mdx": __fd_glob_60, "support/donate.mdx": __fd_glob_61, "support/security.en.mdx": __fd_glob_62, "support/security.mdx": __fd_glob_63, "support/sponsor.en.mdx": __fd_glob_64, "support/sponsor.mdx": __fd_glob_65, });